// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateAnnualFuelCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateAnnualFuelCost'](arg1, arg2, arg3);
}

export function CalculateFuelCost(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateFuelCost'](arg1, arg2, arg3);
}

export function CalculateFuelNeeded(arg1, arg2) {
  return window['go']['main']['App']['CalculateFuelNeeded'](arg1, arg2);
}

export function CalculateMaxDistance(arg1, arg2) {
  return window['go']['main']['App']['CalculateMaxDistance'](arg1, arg2);
}

export function CalculateRoundTrip(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateRoundTrip'](arg1, arg2, arg3);
}

export function CompareFuelCosts(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CompareFuelCosts'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ConvertKmplToMPG(arg1) {
  return window['go']['main']['App']['ConvertKmplToMPG'](arg1);
}

export function ConvertMPGToKmpl(arg1) {
  return window['go']['main']['App']['ConvertMPGToKmpl'](arg1);
}

export function GetFuelEfficiencyCategory(arg1) {
  return window['go']['main']['App']['GetFuelEfficiencyCategory'](arg1);
}

export function Greetings(arg1) {
  return window['go']['main']['App']['Greetings'](arg1);
}
