// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateAnnualFuelCost(arg1:number,arg2:number,arg3:number):Promise<Record<string, number>>;

export function CalculateFuelCost(arg1:number,arg2:number,arg3:number):Promise<main.FuelCalculation>;

export function CalculateFuelNeeded(arg1:number,arg2:number):Promise<number>;

export function CalculateMaxDistance(arg1:number,arg2:number):Promise<number>;

export function CalculateRoundTrip(arg1:number,arg2:number,arg3:number):Promise<main.FuelCalculation>;

export function CompareFuelCosts(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<main.TripComparison>;

export function ConvertKmplToMPG(arg1:number):Promise<number>;

export function ConvertMPGToKmpl(arg1:number):Promise<number>;

export function GetFuelEfficiencyCategory(arg1:number):Promise<string>;

export function Greetings(arg1:string):Promise<string>;
